[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  function = "og-param-proxy"
  path = "/game/*"

[build]
  publish = "steks/dist"
  command = "cargo install trunk --locked; trunk build steks/index.html --release"


[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }